---
# nfs-server/tasks/main.yml
- name: Install nfs
  tags: nfs-server
  yum: name=nfs-utils
  become: true

- name: Create landsat ingest directory
  tags: nfs-server
  file: path=/exports/ingest/landsat state=directory mode=0777
  become: true

- name: Create binary ingest directory
  tags: nfs-server
  file: path=/exports/ingest/binary state=directory mode=0777
  become: true

- name: Create raw directory
  tags: nfs-server
  file: path=/exports/raw state=directory mode=0777
  become: true

- name: Create products directory
  tags: nfs-server
  file: path=/exports/products state=directory mode=0777
  become: true

- name: Configure nfs exports
  tags: nfs-server
  template: src=exports.j2 dest='/etc/exports'
  become: true

- name: Start rpc
  tags: nfs-server
  service: state=started name=rpcbind
  become: true

- name: Start nfs
  tags: nfs-server
  service: state=started name=nfs-server
  become: true

- name: Start nfs-lock
  tags: nfs-server
  service: state=started name=nfs-lock
  become: true

- name: Start nfs-idmap
  tags: nfs-server
  service: state=started name=nfs-idmap
  become: true
