# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 21:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0009_auto_20170412_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='disk_in_required',
            new_name='input_file_size',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='node_required',
        ),
        migrations.AddField(
            model_name='queue',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
