# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0011_auto_20170616_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='cpus_required',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='disk_out_required',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='disk_total_required',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='mem_required',
        ),
    ]
