# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0012_auto_20170616_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='job',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='job_exe',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='job_type',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
