# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 19:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_auto_20170707_1034'),
        ('queue', '0013_auto_20170720_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_num', models.IntegerField()),
                ('input_file_size', models.FloatField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('priority', models.IntegerField(db_index=True)),
                ('timeout', models.IntegerField()),
                ('interface', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resources', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('queued', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.JobType')),
            ],
            options={
                'db_table': 'queue',
            },
        ),
    ]
