# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0017_queue_docker_image'),
        ('job', '0046_jobtyperevision_docker_image'),
    ]

    def populate_job_execution_with_docker_image(apps, schema_editor):
        from job.execution.configuration.json.exe_config import ExecutionConfiguration

        # Go through all of the queued jobs and job executions and update with docker_image value
        Queue = apps.get_model('queue', 'Queue')
        JobExecution = apps.get_model('job', 'JobExecution')

        queue_count = 0
        # Iterate over all queue models and update docker_image
        for queue in Queue.objects.all().select_related('job__job_type_rev'):
            queue.docker_image = queue.job.job_type_rev.docker_image
            queue.save()
            queue_count += 1
            
        job_exe_count = 0
        # Iterate over all job execution models and update docker image
        for job_exe in JobExecution.objects.all().select_related('job__job_type_rev'):
            job_exe.docker_image = job_exe.job.job_type_rev.docker_image
            job_exe.save()
            job_exe_count += 1

        print 'Updated queue models %s with docker_image.' % str(queue_count)
        print 'Updated job_execution models %s with docker_image.' % str(job_exe_count)

    operations = [
        migrations.RunPython(populate_job_execution_with_docker_image),
    ]
