# -*- mode: ruby -*-
# vi: set ft=ruby :

##
# This will provision a couple of machines for a test cluster.
# One will act as zookeeper, master, db, scheduler, and web server.
# The other will be an execution slave.

SLAVE_RAM = 2048
SLAVE_CPUS = 4
NETWORK = "10.4.4."
NETMASK = "255.255.255.0"

HOSTS = {
   "master" => [NETWORK+"10", 1024, 3],
   "slave1" => [NETWORK+"20", SLAVE_RAM, SLAVE_CPUS],
   "slave2" => [NETWORK+"21", SLAVE_RAM, SLAVE_CPUS],
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
   config.hostmanager.enabled = true
   config.hostmanager.manage_host = true
   config.hostmanager.ignore_private_ip = false
   config.hostmanager.include_offline = true

   HOSTS.each do | (name, cfg) |
     ipaddr, ram, cpus = cfg

     config.vm.define name do |machine|
       # centos7 with virtualbox guest additions
       machine.vm.box = "jaredhocutt/centos7"
       # set machine's ram and cpu
       machine.vm.provider "virtualbox" do |vbox|
         vbox.memory = ram
         vbox.cpus = cpus
       end

       # setup network
       machine.vm.hostname = name
       machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK

       if name === "master"
          machine.vm.synced_folder "..", "/scale/"
       end
     end

   end # HOSTS-each

   # run the ansible provisioner. rerun with "vagrant provision"
   config.vm.provision :ansible, run: "always" do |ansible|
     ansible.playbook = '../ansible/vagrant.yml'
     ansible.verbose = 'vv'
     ansible.groups = {
        'zookeeper' => ["master"],
        'mesos-masters' => ["master"],
        'mesos-slaves' => ["slave1","slave2"],
        'db' => ["master"],
        'dns' => ["master"],
        'nfs' => ["master"],
        'registry' => ["master"],
        'build' => ["master"],
        'scale-scheduler' => ["master"],
        'scale-web' => ["master"],
        'mesos:children' => ["mesos-masters", "mesos-slaves"],
        'scale-framework:children' => ["scale-scheduler", "scale-web"],
        'vagrant' => ["master", "slave1", "slave2"]
     }
   end
end
