# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_node_is_paused_errors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='archived',
            new_name='deprecated',
        ),
    ]
