# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20170524_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_paused_errors',
        ),
        migrations.RemoveField(
            model_name='node',
            name='last_offer',
        ),
        migrations.RemoveField(
            model_name='node',
            name='port',
        ),
        migrations.RemoveField(
            model_name='node',
            name='slave_id',
        ),
    ]
