# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20181220_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_offer_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
