# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20170412_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='completed_job_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='completed_recipe_count',
            field=models.IntegerField(default=0),
        ),
    ]
