# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20180122_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('jobs_total', models.IntegerField(default=0)),
                ('jobs_pending', models.IntegerField(default=0)),
                ('jobs_blocked', models.IntegerField(default=0)),
                ('jobs_queued', models.IntegerField(default=0)),
                ('jobs_running', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('jobs_canceled', models.IntegerField(default=0)),
                ('min_alg_duration', models.DurationField(blank=True, null=True)),
                ('avg_alg_duration', models.DurationField(blank=True, null=True)),
                ('max_alg_duration', models.DurationField(blank=True, null=True)),
                ('min_job_duration', models.DurationField(blank=True, null=True)),
                ('avg_job_duration', models.DurationField(blank=True, null=True)),
                ('max_job_duration', models.DurationField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_metrics',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_canceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_queued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_running',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='jobs_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchmetrics',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batch.Batch'),
        ),
        migrations.AlterUniqueTogether(
            name='batchmetrics',
            unique_together=set([('batch', 'job_name')]),
        ),
    ]
