# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 02:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_auto_20180307_1617'),
        ('batch', '0005_auto_20180314_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_creation_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe_type_rev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipe.RecipeTypeRevision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='recipes_estimated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='root_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_batches', to='batch.Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='superseded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='superseded_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_batch', to='batch.Batch'),
        ),
    ]
