"""Provides utility functions for handling Mesos"""
from __future__ import unicode_literals

import json
import logging
from base64 import b64decode
from datetime import datetime, timedelta

from django.utils.timezone import utc

from job.models import TaskUpdate

try:
    from types import SimpleNamespace as Namespace
except ImportError:
    # Python 2.x fallback
    from argparse import Namespace

EPOCH = datetime.utcfromtimestamp(0).replace(tzinfo=utc)


logger = logging.getLogger(__name__)

sample = {u'type': u'UPDATE', u'update': {u'status':
                                              {u'task_id': {
                                                  u'value': u'scale_health_73e84cd0-c07b-44bc-a76b-475f608aa132-0005_10'},
                                               u'timestamp': 1541085060.901,
                                               u'state': u'TASK_LOST',
                                               u'source': u'SOURCE_MASTER',
                                               u'reason': u'REASON_RECONCILIATION',
                                               u'agent_id': {u'value': u'ef554235-4600-4202-aac9-53d79dc8e923-S3'},
                                               u'message': u'Reconciliation: Task is unknown to the agent'}
                                          }}

sample_update = {u'status': {u'executor_id': {u'value': u'scale_message_handler_73e84cd0-c07b-44bc-a76b-475f608aa132-0026_1'}, u'uuid': u'+R4CDr9iQpiUDMadJJUcyQ==', u'task_id': {u'value': u'scale_message_handler_73e84cd0-c07b-44bc-a76b-475f608aa132-0026_1'}, u'timestamp': 1541450313.48904, u'container_status': {u'network_infos': [{u'ip_addresses': [{u'ip_address': u'172.17.0.5', u'protocol': u'IPv4'}]}], u'container_id': {u'value': u'faf4ee25-62c0-4c46-8fcf-c2908b498dfe'}}, u'source': u'SOURCE_EXECUTOR', u'state': u'TASK_RUNNING', u'agent_id': {u'value': u'ef554235-4600-4202-aac9-53d79dc8e923-S6'}, u'data': u'WwogICAgewogICAgICAgICJJZCI6ICIyMmYyYzJkZDgyNTY0MTNhZWUzY2VmYTM0MGQzNTZkYjA5ZTE4ZDJiOWRiNzI1NjRhYmE4MWQ5M2MzZjU5OTE0IiwKICAgICAgICAiQ3JlYXRlZCI6ICIyMDE4LTExLTA1VDIwOjM4OjMxLjg4NjM1OTMzN1oiLAogICAgICAgICJQYXRoIjogIi4vZW50cnlQb2ludC5zaCIsCiAgICAgICAgIkFyZ3MiOiBbCiAgICAgICAgICAgICJzY2FsZV9tZXNzYWdlX2hhbmRsZXIiCiAgICAgICAgXSwKICAgICAgICAiU3RhdGUiOiB7CiAgICAgICAgICAgICJTdGF0dXMiOiAicnVubmluZyIsCiAgICAgICAgICAgICJSdW5uaW5nIjogdHJ1ZSwKICAgICAgICAgICAgIlBhdXNlZCI6IGZhbHNlLAogICAgICAgICAgICAiUmVzdGFydGluZyI6IGZhbHNlLAogICAgICAgICAgICAiT09NS2lsbGVkIjogZmFsc2UsCiAgICAgICAgICAgICJEZWFkIjogZmFsc2UsCiAgICAgICAgICAgICJQaWQiOiAxNjUxNCwKICAgICAgICAgICAgIkV4aXRDb2RlIjogMCwKICAgICAgICAgICAgIkVycm9yIjogIiIsCiAgICAgICAgICAgICJTdGFydGVkQXQiOiAiMjAxOC0xMS0wNVQyMDozODozMy4zNzE1NzA1MjhaIiwKICAgICAgICAgICAgIkZpbmlzaGVkQXQiOiAiMDAwMS0wMS0wMVQwMDowMDowMFoiCiAgICAgICAgfSwKICAgICAgICAiSW1hZ2UiOiAic2hhMjU2OmYzNGJiM2VmMTU2NWRkMDc1OTg1NTU4NjRkYWYwYjNlYTc2ZGNjY2FmZThhZDg4NDEzNGMzY2JmNzBkMWYxZmMiLAogICAgICAgICJSZXNvbHZDb25mUGF0aCI6ICIvdmFyL2xpYi9kb2NrZXIvY29udGFpbmVycy8yMmYyYzJkZDgyNTY0MTNhZWUzY2VmYTM0MGQzNTZkYjA5ZTE4ZDJiOWRiNzI1NjRhYmE4MWQ5M2MzZjU5OTE0L3Jlc29sdi5jb25mIiwKICAgICAgICAiSG9zdG5hbWVQYXRoIjogIi92YXIvbGliL2RvY2tlci9jb250YWluZXJzLzIyZjJjMmRkODI1NjQxM2FlZTNjZWZhMzQwZDM1NmRiMDllMThkMmI5ZGI3MjU2NGFiYTgxZDkzYzNmNTk5MTQvaG9zdG5hbWUiLAogICAgICAgICJIb3N0c1BhdGgiOiAiL3Zhci9saWIvZG9ja2VyL2NvbnRhaW5lcnMvMjJmMmMyZGQ4MjU2NDEzYWVlM2NlZmEzNDBkMzU2ZGIwOWUxOGQyYjlkYjcyNTY0YWJhODFkOTNjM2Y1OTkxNC9ob3N0cyIsCiAgICAgICAgIkxvZ1BhdGgiOiAiL3Zhci9saWIvZG9ja2VyL2NvbnRhaW5lcnMvMjJmMmMyZGQ4MjU2NDEzYWVlM2NlZmEzNDBkMzU2ZGIwOWUxOGQyYjlkYjcyNTY0YWJhODFkOTNjM2Y1OTkxNC8yMmYyYzJkZDgyNTY0MTNhZWUzY2VmYTM0MGQzNTZkYjA5ZTE4ZDJiOWRiNzI1NjRhYmE4MWQ5M2MzZjU5OTE0LWpzb24ubG9nIiwKICAgICAgICAiTmFtZSI6ICIvbWVzb3MtZmFmNGVlMjUtNjJjMC00YzQ2LThmY2YtYzI5MDhiNDk4ZGZlIiwKICAgICAgICAiUmVzdGFydENvdW50IjogMCwKICAgICAgICAiRHJpdmVyIjogIm92ZXJsYXkyIiwKICAgICAgICAiUGxhdGZvcm0iOiAibGludXgiLAogICAgICAgICJNb3VudExhYmVsIjogIiIsCiAgICAgICAgIlByb2Nlc3NMYWJlbCI6ICIiLAogICAgICAgICJBcHBBcm1vclByb2ZpbGUiOiAiIiwKICAgICAgICAiRXhlY0lEcyI6IG51bGwsCiAgICAgICAgIkhvc3RDb25maWciOiB7CiAgICAgICAgICAgICJCaW5kcyI6IFsKICAgICAgICAgICAgICAgICIvdmFyL2xpYi9tZXNvcy9zbGF2ZS9zbGF2ZXMvZWY1NTQyMzUtNDYwMC00MjAyLWFhYzktNTNkNzlkYzhlOTIzLVM2L2ZyYW1ld29ya3MvNzNlODRjZDAtYzA3Yi00NGJjLWE3NmItNDc1ZjYwOGFhMTMyLTAwMjYvZXhlY3V0b3JzL3NjYWxlX21lc3NhZ2VfaGFuZGxlcl83M2U4NGNkMC1jMDdiLTQ0YmMtYTc2Yi00NzVmNjA4YWExMzItMDAyNl8xL3J1bnMvZmFmNGVlMjUtNjJjMC00YzQ2LThmY2YtYzI5MDhiNDk4ZGZlOi9tbnQvbWVzb3Mvc2FuZGJveCIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgIkNvbnRhaW5lcklERmlsZSI6ICIiLAogICAgICAgICAgICAiTG9nQ29uZmlnIjogewogICAgICAgICAgICAgICAgIlR5cGUiOiAianNvbi1maWxlIiwKICAgICAgICAgICAgICAgICJDb25maWciOiB7fQogICAgICAgICAgICB9LAogICAgICAgICAgICAiTmV0d29ya01vZGUiOiAiYnJpZGdlIiwKICAgICAgICAgICAgIlBvcnRCaW5kaW5ncyI6IHt9LAogICAgICAgICAgICAiUmVzdGFydFBvbGljeSI6IHsKICAgICAgICAgICAgICAgICJOYW1lIjogIm5vIiwKICAgICAgICAgICAgICAgICJNYXhpbXVtUmV0cnlDb3VudCI6IDAKICAgICAgICAgICAgfSwKICAgICAgICAgICAgIkF1dG9SZW1vdmUiOiBmYWxzZSwKICAgICAgICAgICAgIlZvbHVtZURyaXZlciI6ICIiLAogICAgICAgICAgICAiVm9sdW1lc0Zyb20iOiBudWxsLAogICAgICAgICAgICAiQ2FwQWRkIjogbnVsbCwKICAgICAgICAgICAgIkNhcERyb3AiOiBudWxsLAogICAgICAgICAgICAiRG5zIjogW10sCiAgICAgICAgICAgICJEbnNPcHRpb25zIjogW10sCiAgICAgICAgICAgICJEbnNTZWFyY2giOiBbXSwKICAgICAgICAgICAgIkV4dHJhSG9zdHMiOiBudWxsLAogICAgICAgICAgICAiR3JvdXBBZGQiOiBudWxsLAogICAgICAgICAgICAiSXBjTW9kZSI6ICJzaGFyZWFibGUiLAogICAgICAgICAgICAiQ2dyb3VwIjogIiIsCiAgICAgICAgICAgICJMaW5rcyI6IG51bGwsCiAgICAgICAgICAgICJPb21TY29yZUFkaiI6IDAsCiAgICAgICAgICAgICJQaWRNb2RlIjogIiIsCiAgICAgICAgICAgICJQcml2aWxlZ2VkIjogZmFsc2UsCiAgICAgICAgICAgICJQdWJsaXNoQWxsUG9ydHMiOiBmYWxzZSwKICAgICAgICAgICAgIlJlYWRvbmx5Um9vdGZzIjogZmFsc2UsCiAgICAgICAgICAgICJTZWN1cml0eU9wdCI6IG51bGwsCiAgICAgICAgICAgICJVVFNNb2RlIjogIiIsCiAgICAgICAgICAgICJVc2VybnNNb2RlIjogIiIsCiAgICAgICAgICAgICJTaG1TaXplIjogNjcxMDg4NjQsCiAgICAgICAgICAgICJSdW50aW1lIjogInJ1bmMiLAogICAgICAgICAgICAiQ29uc29sZVNpemUiOiBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgMAogICAgICAgICAgICBdLAogICAgICAgICAgICAiSXNvbGF0aW9uIjogIiIsCiAgICAgICAgICAgICJDcHVTaGFyZXMiOiA1MTIsCiAgICAgICAgICAgICJNZW1vcnkiOiA1MzY4NzA5MTIsCiAgICAgICAgICAgICJOYW5vQ3B1cyI6IDAsCiAgICAgICAgICAgICJDZ3JvdXBQYXJlbnQiOiAiIiwKICAgICAgICAgICAgIkJsa2lvV2VpZ2h0IjogMCwKICAgICAgICAgICAgIkJsa2lvV2VpZ2h0RGV2aWNlIjogW10sCiAgICAgICAgICAgICJCbGtpb0RldmljZVJlYWRCcHMiOiBudWxsLAogICAgICAgICAgICAiQmxraW9EZXZpY2VXcml0ZUJwcyI6IG51bGwsCiAgICAgICAgICAgICJCbGtpb0RldmljZVJlYWRJT3BzIjogbnVsbCwKICAgICAgICAgICAgIkJsa2lvRGV2aWNlV3JpdGVJT3BzIjogbnVsbCwKICAgICAgICAgICAgIkNwdVBlcmlvZCI6IDAsCiAgICAgICAgICAgICJDcHVRdW90YSI6IDUwMDAwLAogICAgICAgICAgICAiQ3B1UmVhbHRpbWVQZXJpb2QiOiAwLAogICAgICAgICAgICAiQ3B1UmVhbHRpbWVSdW50aW1lIjogMCwKICAgICAgICAgICAgIkNwdXNldENwdXMiOiAiIiwKICAgICAgICAgICAgIkNwdXNldE1lbXMiOiAiIiwKICAgICAgICAgICAgIkRldmljZXMiOiBbXSwKICAgICAgICAgICAgIkRldmljZUNncm91cFJ1bGVzIjogbnVsbCwKICAgICAgICAgICAgIkRpc2tRdW90YSI6IDAsCiAgICAgICAgICAgICJLZXJuZWxNZW1vcnkiOiAwLAogICAgICAgICAgICAiTWVtb3J5UmVzZXJ2YXRpb24iOiAwLAogICAgICAgICAgICAiTWVtb3J5U3dhcCI6IDEwNzM3NDE4MjQsCiAgICAgICAgICAgICJNZW1vcnlTd2FwcGluZXNzIjogbnVsbCwKICAgICAgICAgICAgIk9vbUtpbGxEaXNhYmxlIjogZmFsc2UsCiAgICAgICAgICAgICJQaWRzTGltaXQiOiAwLAogICAgICAgICAgICAiVWxpbWl0cyI6IG51bGwsCiAgICAgICAgICAgICJDcHVDb3VudCI6IDAsCiAgICAgICAgICAgICJDcHVQZXJjZW50IjogMCwKICAgICAgICAgICAgIklPTWF4aW11bUlPcHMiOiAwLAogICAgICAgICAgICAiSU9NYXhpbXVtQmFuZHdpZHRoIjogMCwKICAgICAgICAgICAgIk1hc2tlZFBhdGhzIjogWwogICAgICAgICAgICAgICAgIi9wcm9jL2FjcGkiLAogICAgICAgICAgICAgICAgIi9wcm9jL2tjb3JlIiwKICAgICAgICAgICAgICAgICIvcHJvYy9rZXlzIiwKICAgICAgICAgICAgICAgICIvcHJvYy9sYXRlbmN5X3N0YXRzIiwKICAgICAgICAgICAgICAgICIvcHJvYy90aW1lcl9saXN0IiwKICAgICAgICAgICAgICAgICIvcHJvYy90aW1lcl9zdGF0cyIsCiAgICAgICAgICAgICAgICAiL3Byb2Mvc2NoZWRfZGVidWciLAogICAgICAgICAgICAgICAgIi9wcm9jL3Njc2kiLAogICAgICAgICAgICAgICAgIi9zeXMvZmlybXdhcmUiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJSZWFkb25seVBhdGhzIjogWwogICAgICAgICAgICAgICAgIi9wcm9jL2Fzb3VuZCIsCiAgICAgICAgICAgICAgICAiL3Byb2MvYnVzIiwKICAgICAgICAgICAgICAgICIvcHJvYy9mcyIsCiAgICAgICAgICAgICAgICAiL3Byb2MvaXJxIiwKICAgICAgICAgICAgICAgICIvcHJvYy9zeXMiLAogICAgICAgICAgICAgICAgIi9wcm9jL3N5c3JxLXRyaWdnZXIiCiAgICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgICJHcmFwaERyaXZlciI6IHsKICAgICAgICAgICAgIkRhdGEiOiB7CiAgICAgICAgICAgICAgICAiTG93ZXJEaXIiOiAiL3Zhci9saWIvZG9ja2VyL292ZXJsYXkyL2Q4MDE2YWIxZmRjZjJmNmM4YjQwOGZhYTIwYTBmYWUwYWNjY2U4NWQzZDI4YzgwNTI3OTFjMjI3ODE5NDNkMWQtaW5pdC9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi82ZjhkNDU0MjUyNzUwMDNjZjUwNTI2NDFiOTZhODZiYjA5OTU0YjZjMjFmMmUwZGZlNTYyMTBkYWUyMTk4ODhlL2RpZmY6L3Zhci9saWIvZG9ja2VyL292ZXJsYXkyLzk0ZTI0YjEyOTk0MGY4ZGQ2NDk1NTRjMmVkOGQ2YzY1ZmRhNjdlZDI0OGQ2YWQxY2Y1Yjc4NjkyMWEzYTBkMTUvZGlmZjovdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvZmVjNzBmMjliNzY0MDFjMDI5ZjM1YjE2NmNhNmRlMDU5NWZjYTE1NjEwNDg4ODQ5N2ZiMTJiZTE1N2ExNjU2ZC9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi9kZDJlZjhhZGRiOWJmNGY5MDg0YzgwMzAyYWYxMmQzZWI4ZTNlZjdjMDM4YWQ1ZThiNDE0ZTZlYTdhMTZmNWYzL2RpZmY6L3Zhci9saWIvZG9ja2VyL292ZXJsYXkyLzcyNzU4Y2Q1OGIwMzczMzU4Mjk1NzBhOWM0M2ZlY2Y0OGNkMDcyOTM3MjFkMzhhYWY2NmQ0ZWNiNTk3ZGNmZjkvZGlmZjovdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvODA1MTA1NzEyYmMxYjI3NTNlM2E5YmNjMGNkYTA5Y2UwOWEyODUyMWI3YjhkNjgzZTk1MTg3ZTg0YzE2YzBkOC9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi9kYzMwZGM1MzQzMWJiMGQ4Y2EwMjA2ZDgwZDEwYTAzMzc0ZjhiMTM1MzNmNjZmZjM4NWEyN2I1ODg3YjBkODNjL2RpZmY6L3Zhci9saWIvZG9ja2VyL292ZXJsYXkyLzM0NzYxY2UxZTgyN2UyZWRhMjUyM2E0M2I5MWMxM2NmZjNkMzg1ZjA5NThlNGFlZWRlN2Y4NGU5NzZjMGU5ZTEvZGlmZjovdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvNTQ4NjZkODg5NTMyNzQyYzZiNmEyYTU1NTUxNmM1MjExMTBjNDM0NzA1M2ZiZmU0YTAwYjg5OGJjMjA5MzdmZi9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi82OGYyM2EyMTZlMmIyOGE4NDRlMTg3YTgyMGU2ODU3ZjY3YmJmMjNlNzJlN2FiNDY5NjFjMWJhMTUwMjM2NDJiL2RpZmY6L3Zhci9saWIvZG9ja2VyL292ZXJsYXkyLzdlMmViMTA5ZDI2MDMwYzkzNDI1YzZlMTM4MjQ5MDJkNDQ3N2NhNjM5NWFiZjYyNzk2YjNmNGQxZGZlODQ0OGQvZGlmZjovdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvMTA0ZGMyOTdmMjYzNDViZTk5Yjg4NGRmNmZjY2VhYTc2OGMwM2U2OGFjZjA1ZTFiZDgwZjM3ZmQ3ZTJlNGMwNy9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi9iMmQwNjExNmU5NjFlMTljODRlNTEwNGIyOGRmZmE5OThiMTliZjNmZDg1NGU1ZDM0Mjc1NTRiNjIyZTIwODJjL2RpZmY6L3Zhci9saWIvZG9ja2VyL292ZXJsYXkyLzkxZGFkNTY2MjZiMmRkZjNjNjQ5MTUwNmUyNTMxOTE2OTM1MGQxZDUxZTBlODQ2YjUzYjhhZWMzMTMxMzNhZTcvZGlmZjovdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvZjQ2MmFmMTg2NWYwY2Q0ZTRjMGQzNTI2MDg2OWVkYzBmYWE0MWVjOWUzZDY5MWI1OGE0ZThhMGU1ZGUzYmFjOS9kaWZmOi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi81N2FhMzA5MjJkYTdlNDM0YTczZTRhZGE2MzAwOGFmNWIxY2FjMTc5Nzk4OWZhNjRjMWU0ZjhmM2VhNDFiN2QwL2RpZmYiLAogICAgICAgICAgICAgICAgIk1lcmdlZERpciI6ICIvdmFyL2xpYi9kb2NrZXIvb3ZlcmxheTIvZDgwMTZhYjFmZGNmMmY2YzhiNDA4ZmFhMjBhMGZhZTBhY2NjZTg1ZDNkMjhjODA1Mjc5MWMyMjc4MTk0M2QxZC9tZXJnZWQiLAogICAgICAgICAgICAgICAgIlVwcGVyRGlyIjogIi92YXIvbGliL2RvY2tlci9vdmVybGF5Mi9kODAxNmFiMWZkY2YyZjZjOGI0MDhmYWEyMGEwZmFlMGFjY2NlODVkM2QyOGM4MDUyNzkxYzIyNzgxOTQzZDFkL2RpZmYiLAogICAgICAgICAgICAgICAgIldvcmtEaXIiOiAiL3Zhci9saWIvZG9ja2VyL292ZXJsYXkyL2Q4MDE2YWIxZmRjZjJmNmM4YjQwOGZhYTIwYTBmYWUwYWNjY2U4NWQzZDI4YzgwNTI3OTFjMjI3ODE5NDNkMWQvd29yayIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgIk5hbWUiOiAib3ZlcmxheTIiCiAgICAgICAgfSwKICAgICAgICAiTW91bnRzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiVHlwZSI6ICJiaW5kIiwKICAgICAgICAgICAgICAgICJTb3VyY2UiOiAiL3Zhci9saWIvbWVzb3Mvc2xhdmUvc2xhdmVzL2VmNTU0MjM1LTQ2MDAtNDIwMi1hYWM5LTUzZDc5ZGM4ZTkyMy1TNi9mcmFtZXdvcmtzLzczZTg0Y2QwLWMwN2ItNDRiYy1hNzZiLTQ3NWY2MDhhYTEzMi0wMDI2L2V4ZWN1dG9ycy9zY2FsZV9tZXNzYWdlX2hhbmRsZXJfNzNlODRjZDAtYzA3Yi00NGJjLWE3NmItNDc1ZjYwOGFhMTMyLTAwMjZfMS9ydW5zL2ZhZjRlZTI1LTYyYzAtNGM0Ni04ZmNmLWMyOTA4YjQ5OGRmZSIsCiAgICAgICAgICAgICAgICAiRGVzdGluYXRpb24iOiAiL21udC9tZXNvcy9zYW5kYm94IiwKICAgICAgICAgICAgICAgICJNb2RlIjogIiIsCiAgICAgICAgICAgICAgICAiUlciOiB0cnVlLAogICAgICAgICAgICAgICAgIlByb3BhZ2F0aW9uIjogInJwcml2YXRlIgogICAgICAgICAgICB9CiAgICAgICAgXSwKICAgICAgICAiQ29uZmlnIjogewogICAgICAgICAgICAiSG9zdG5hbWUiOiAiMjJmMmMyZGQ4MjU2IiwKICAgICAgICAgICAgIkRvbWFpbm5hbWUiOiAiIiwKICAgICAgICAgICAgIlVzZXIiOiAiIiwKICAgICAgICAgICAgIkF0dGFjaFN0ZGluIjogZmFsc2UsCiAgICAgICAgICAgICJBdHRhY2hTdGRvdXQiOiB0cnVlLAogICAgICAgICAgICAiQXR0YWNoU3RkZXJyIjogdHJ1ZSwKICAgICAgICAgICAgIkV4cG9zZWRQb3J0cyI6IHsKICAgICAgICAgICAgICAgICI4MC90Y3AiOiB7fQogICAgICAgICAgICB9LAogICAgICAgICAgICAiVHR5IjogZmFsc2UsCiAgICAgICAgICAgICJPcGVuU3RkaW4iOiBmYWxzZSwKICAgICAgICAgICAgIlN0ZGluT25jZSI6IGZhbHNlLAogICAgICAgICAgICAiRW52IjogWwogICAgICAgICAgICAgICAgIlNDQUxFX0RCX05BTUU9c2NhbGUiLAogICAgICAgICAgICAgICAgIlNDQUxFX0RCX1VTRVI9c2NhbGUiLAogICAgICAgICAgICAgICAgIlNDQUxFX0RCX1BBU1M9c2NhbGUiLAogICAgICAgICAgICAgICAgIlNDQUxFX1FVRVVFX05BTUU9c2NhbGUtY29tbWFuZC1tZXNzYWdlcyIsCiAgICAgICAgICAgICAgICAiTElCUFJPQ0VTU19JUD0xMC4zLjIuMTg5IiwKICAgICAgICAgICAgICAgICJNRVNPU19DT05UQUlORVJfTkFNRT1tZXNvcy1mYWY0ZWUyNS02MmMwLTRjNDYtOGZjZi1jMjkwOGI0OThkZmUiLAogICAgICAgICAgICAgICAgIk1FU09TX1NBTkRCT1g9L21udC9tZXNvcy9zYW5kYm94IiwKICAgICAgICAgICAgICAgICJTQ0FMRV9EQl9IT1NUPTEwLjMuMi4xODQiLAogICAgICAgICAgICAgICAgIlNDQUxFX0RCX1BPUlQ9Mjc2MTkiLAogICAgICAgICAgICAgICAgIlNDQUxFX0JST0tFUl9VUkw9YW1xcDovL2d1ZXN0Omd1ZXN0QCBzY2FsZS1yYWJiaXRtcS5tYXJhdGhvbi5sNGxiLnRoaXNkY29zLmRpcmVjdG9yeTo1NjcyIiwKICAgICAgICAgICAgICAgICJQQVRIPS91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbiIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgIkNtZCI6IFsKICAgICAgICAgICAgICAgICJzY2FsZV9tZXNzYWdlX2hhbmRsZXIiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJJbWFnZSI6ICJsb2NhbGhvc3Q6NTAwMC9naXNqZWRpL3NjYWxlIiwKICAgICAgICAgICAgIlZvbHVtZXMiOiBudWxsLAogICAgICAgICAgICAiV29ya2luZ0RpciI6ICIvb3B0L3NjYWxlIiwKICAgICAgICAgICAgIkVudHJ5cG9pbnQiOiBbCiAgICAgICAgICAgICAgICAiLi9lbnRyeVBvaW50LnNoIgogICAgICAgICAgICBdLAogICAgICAgICAgICAiT25CdWlsZCI6IG51bGwsCiAgICAgICAgICAgICJMYWJlbHMiOiB7CiAgICAgICAgICAgICAgICAiREVTQ1JJUFRJT04iOiAiUHJvY2Vzc2luZyBmcmFtZXdvcmsgZm9yIGNvbnRhaW5lcml6ZWQgYWxnb3JpdGhtcyIsCiAgICAgICAgICAgICAgICAiUlVOIjogImRvY2tlciBydW4gLWQgZ2VvaW50L3NjYWxlIHNjYWxlX3NjaGVkdWxlciIsCiAgICAgICAgICAgICAgICAiU09VUkNFIjogImh0dHBzOi8vZ2l0aHViLmNvbS9uZ2FnZW9pbnQvc2NhbGUiLAogICAgICAgICAgICAgICAgImJ1aWxkLWRhdGUiOiAiMjAxNzA5MTEiLAogICAgICAgICAgICAgICAgImxpY2Vuc2UiOiAiR1BMdjIiLAogICAgICAgICAgICAgICAgIm5hbWUiOiAiQ2VudE9TIEJhc2UgSW1hZ2UiLAogICAgICAgICAgICAgICAgInZlbmRvciI6ICJDZW50T1MiCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJOZXR3b3JrU2V0dGluZ3MiOiB7CiAgICAgICAgICAgICJCcmlkZ2UiOiAiIiwKICAgICAgICAgICAgIlNhbmRib3hJRCI6ICI1NDk5ZDlkYWU5N2U0YjJiNzM4MzczOTQ4N2IwOTUzMTE0YWFlMzBkZjM5NWVhMjQ4MjMxOWM5NDlmYTZlOTliIiwKICAgICAgICAgICAgIkhhaXJwaW5Nb2RlIjogZmFsc2UsCiAgICAgICAgICAgICJMaW5rTG9jYWxJUHY2QWRkcmVzcyI6ICIiLAogICAgICAgICAgICAiTGlua0xvY2FsSVB2NlByZWZpeExlbiI6IDAsCiAgICAgICAgICAgICJQb3J0cyI6IHsKICAgICAgICAgICAgICAgICI4MC90Y3AiOiBudWxsCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJTYW5kYm94S2V5IjogIi92YXIvcnVuL2RvY2tlci9uZXRucy81NDk5ZDlkYWU5N2UiLAogICAgICAgICAgICAiU2Vjb25kYXJ5SVBBZGRyZXNzZXMiOiBudWxsLAogICAgICAgICAgICAiU2Vjb25kYXJ5SVB2NkFkZHJlc3NlcyI6IG51bGwsCiAgICAgICAgICAgICJFbmRwb2ludElEIjogIjkzOWYzMWRkMDc4NzJlZjU4MGU2MWY3OTQxYTEyMTFiZDA4YTJiOTIxM2I0MTUyMGM2Y2MzZTBlN2JjZDNkY2QiLAogICAgICAgICAgICAiR2F0ZXdheSI6ICIxNzIuMTcuMC4xIiwKICAgICAgICAgICAgIkdsb2JhbElQdjZBZGRyZXNzIjogIiIsCiAgICAgICAgICAgICJHbG9iYWxJUHY2UHJlZml4TGVuIjogMCwKICAgICAgICAgICAgIklQQWRkcmVzcyI6ICIxNzIuMTcuMC41IiwKICAgICAgICAgICAgIklQUHJlZml4TGVuIjogMTYsCiAgICAgICAgICAgICJJUHY2R2F0ZXdheSI6ICIiLAogICAgICAgICAgICAiTWFjQWRkcmVzcyI6ICIwMjo0MjphYzoxMTowMDowNSIsCiAgICAgICAgICAgICJOZXR3b3JrcyI6IHsKICAgICAgICAgICAgICAgICJicmlkZ2UiOiB7CiAgICAgICAgICAgICAgICAgICAgIklQQU1Db25maWciOiBudWxsLAogICAgICAgICAgICAgICAgICAgICJMaW5rcyI6IG51bGwsCiAgICAgICAgICAgICAgICAgICAgIkFsaWFzZXMiOiBudWxsLAogICAgICAgICAgICAgICAgICAgICJOZXR3b3JrSUQiOiAiZjkyZWZhZDBhMDAxMDM0ZWNjMmE1OGJlNWU3MmI2M2FhYmU2NzJjMmRmNGNmNDg0OTI5MTFlODcxNDhiNDVhNSIsCiAgICAgICAgICAgICAgICAgICAgIkVuZHBvaW50SUQiOiAiOTM5ZjMxZGQwNzg3MmVmNTgwZTYxZjc5NDFhMTIxMWJkMDhhMmI5MjEzYjQxNTIwYzZjYzNlMGU3YmNkM2RjZCIsCiAgICAgICAgICAgICAgICAgICAgIkdhdGV3YXkiOiAiMTcyLjE3LjAuMSIsCiAgICAgICAgICAgICAgICAgICAgIklQQWRkcmVzcyI6ICIxNzIuMTcuMC41IiwKICAgICAgICAgICAgICAgICAgICAiSVBQcmVmaXhMZW4iOiAxNiwKICAgICAgICAgICAgICAgICAgICAiSVB2NkdhdGV3YXkiOiAiIiwKICAgICAgICAgICAgICAgICAgICAiR2xvYmFsSVB2NkFkZHJlc3MiOiAiIiwKICAgICAgICAgICAgICAgICAgICAiR2xvYmFsSVB2NlByZWZpeExlbiI6IDAsCiAgICAgICAgICAgICAgICAgICAgIk1hY0FkZHJlc3MiOiAiMDI6NDI6YWM6MTE6MDA6MDUiLAogICAgICAgICAgICAgICAgICAgICJEcml2ZXJPcHRzIjogbnVsbAogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQpdCg=='}}


def obj_from_json(input_json):
    """Converts an JSON dict into a dot accessible object

    :param input_json: The task status in TaskStatus JSON format
    :type input_json: dict
    :returns: The Task Status in dot accessible form
    :rtype: :class:`Namespace`
    """
    return json.loads(json.dumps(input_json), object_hook=lambda d: Namespace(**d))


def create_task_update_model(status):
    """Creates and returns a task update model for the given Mesos task status

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task update model
    :rtype: :class:`job.models.TaskUpdate`
    """

    task_update = TaskUpdate()
    task_update.task_id = get_status_task_id(status)
    task_update.status = get_status_state(status)
    task_update.timestamp = get_status_timestamp(status)
    task_update.source = get_status_source(status)
    task_update.reason = get_status_reason(status)
    task_update.message = get_status_message(status)

    return task_update


def get_status_agent_id(status):
    """Returns the agent ID of the given Mesos task status

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The agent ID
    :rtype: string
    """

    return obj_from_json(status).status.agent_id.value


def get_status_data(status):
    """Returns the data dict in the given Mesos task status. If there is no data dict or it is invalid, an empty dict
    will be returned.

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task status data dict
    :rtype: dict
    """

    data = {}

    try:
        data = json.loads(b64decode(obj_from_json(status).status.data))
    except AttributeError:
        pass
    except:
        logger.exception('Invalid data dict')

    return data


def get_status_message(status):
    """Returns the message of the given Mesos task status, possibly None

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task status message
    :rtype: string
    """

    message = None
    try:
        message = obj_from_json(status).status.message
    except AttributeError:
        pass

    return message


def get_status_reason(status):
    """Returns the reason of the given Mesos task status, possibly None

    :param status: The task status in TaskInfo JSON format
    :type status: dict
    :returns: The task status reason
    :rtype: string
    """

    reason = None
    try:
        reason = obj_from_json(status).status.reason
    except AttributeError:
        pass

    return reason


def get_status_source(status):
    """Returns the source of the given Mesos task status, possibly None

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task status source
    :rtype: string
    """

    return obj_from_json(status).status.source


def get_status_state(status):
    """Returns the state of the given Mesos task status, possibly None

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task status state
    :rtype: string
    """

    return obj_from_json(status).status.state


def get_status_task_id(status):
    """Returns the task ID of the given Mesos task status

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task ID
    :rtype: string
    """

    return obj_from_json(status).status.task_id.value


def get_status_timestamp(status):
    """Returns the timestamp of the given Mesos task status, possibly None

    :param status: The task status in TaskStatus JSON format
    :type status: dict
    :returns: The task status timestamp
    :rtype: :class:`datetime.datetime`
    """

    timestamp = obj_from_json(status).status.timestamp
    if timestamp:
        return EPOCH + timedelta(seconds=timestamp)

    return None
