# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20170412_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipefile',
            name='recipe_input',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
