# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_recipetype_is_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='data',
            new_name='input',
        ),
    ]
