# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20180122_1444'),
        ('recipe', '0019_recipetype_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes_for_batch', to='batch.Batch'),
        ),
    ]
