# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_recipe_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='input_file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
