# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_auto_20180523_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_recipes', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='root_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_recipes_for_root', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_recipes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_recipes_total',
            field=models.IntegerField(default=0),
        ),
    ]
