# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0028_auto_20181016_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
