# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0049_auto_20180927_1531'),
        ('recipe', '0029_auto_20181016_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTypeJobLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_types_for_recipe_type', to='job.JobType')),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_types_for_job_type', to='recipe.RecipeType')),
            ],
            options={
                'db_table': 'recipe_type_job_link',
            },
        ),
        migrations.CreateModel(
            name='RecipeTypeSubLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_recipe_type', to='recipe.RecipeType')),
                ('sub_recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_recipe_type', to='recipe.RecipeType')),
            ],
            options={
                'db_table': 'recipe_type_sub_link',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipetypesublink',
            unique_together=set([('recipe_type', 'sub_recipe_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipetypejoblink',
            unique_together=set([('recipe_type', 'job_type')]),
        ),
    ]
