# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0032_recipe_type_link_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetype',
            old_name='archived',
            new_name='deprecated',
        ),
    ]
