# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-20 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_auto_20181102_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
