# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0035_auto_20190126_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetype',
            name='version',
        ),
    ]
