# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0036_remove_recipetype_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetype',
            name='trigger_rule',
        ),
    ]
