# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0037_remove_recipetype_trigger_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenode',
            name='job',
        ),
        migrations.RemoveField(
            model_name='recipenode',
            name='sub_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes_for_recipe_node', to='recipe.RecipeNode'),
        ),
    ]
