# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0039_multiple_jobs_per_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenode',
            name='job',
        ),
        migrations.RemoveField(
            model_name='recipenode',
            name='sub_recipe',
        )
    ]
