"""Defines the QueueEventProcessor for generating file ancestry links as job executions change status."""
from product.models import ProductFile
from queue.models import QueueEventProcessor


class ProductProcessor(QueueEventProcessor):
    """This class creates file ancestry links when a job execution is queued or completed."""

    def process_queued(self, job_exe, is_initial):
        """See :meth:`queue.models.QueueEventProcessor.process_queued`.

        Creates file ancestry links for all source files and their ancestry needed to run the job execution.
        """
        pass

    def process_completed(self, job_exe):
        """See :meth:`queue.models.QueueEventProcessor.process_completed`.

        Creates file ancestry links for all products generated by a job execution, including the source file ancestry.
        """
        pass

    def process_failed(self, job_exe):
        """See :meth:`queue.models.QueueEventProcessor.process_failed`.

        Not used by this class.
        """
        pass
