openapi: "3.0.0"
info:
  title: Error Services
  version: v6
paths:
  /errors/:
    get:
      operationId: _rest_v6_error_list
      summary: Error List
      description: Returns a list of all errors
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        - in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results.
            Defaults to 100, and can be anywhere from 1-1000.
        - in: query
          name: started
          schema:
            type: string
            format: date-time
          description: The start of the time range to query
        - in: query
          name: ended
          schema:
            type: string
            format: date-time
          description: End of the time range to query, defaults to the current time
        - in: query
          name: is_builtin
          schema:
            type: boolean
          description: if provided, only return errors matching is_builtin
        - in: query
          name: job_type_name
          schema:
            type: string
          description: if provided, only return errors for job types with the given name (any version)
        - in: query
          name: name
          schema:
            type: string
          description: if provided, only return errors with the given name
        - in: query
          name: category
          schema:
            type: string
          description: if provided, only return errors matching the given category
        - in: query
          name: order
          schema:
            type: string
          description: "One or more fields to use when ordering the results. |
                        Duplicate it to multi-sort, (ex: order=host_name&order=created) |
                        Nested objects require a delimiter (ex: order=source_file__created) |
                        Prefix fields with a dash to reverse the sort, (ex: order=-created)"
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/error_list'

  /ingests/errors/{id}/:
    get:
      operationId: _rest_v6_error_details
      summary: Error Details
      description: Returns detailed information about the error with the specified id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: id of an existing error
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/error_details'

components:
  schemas:
    error_list:
      title: Error List
      type: object
      properties:
        count:
          type: integer
          description: The total number of results that match the query parameters 
          example: 10
        next:
          type: string
          format: uri
          description: A URL to the next page of results.
          example: null
        previous:
          type: string
          format: uri
          description: A URL to the previous page of results.
          example: null
        results:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
          description: List of Error objects
    error_base:
      title: Error Base
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: my-error
        title:
          type: string
          example: My Error
        description:
          type: string
          example: My Error Description 
        job_type_name:
          type: string
          description: The name of the job type that relates to this error.
          example: job-type
        category:
          type: string
          example: SYSTEM 
        is_builtin:
          type: boolean
          description: Whether the error was loaded during the installation process.
          example: true
        should_be_retried:
          type: boolean
          description: Whether jobs with this error should be retried automatically. |
            The following builtin errors are retried automatically: Unknown, |
            Database, Database Operation, Filesystem I/O, Ingest Timeout, Task Launch,|
            Docker Launch, Docker Terminated, Node Lost, Resource Starvation, |
            Launch Timeout, Pull-task Timeout, Pre-task Timeout, Post-task Timeout, |
            Timeout (System), Docker Pull Failed, Scheduler Restarted
          example: true
    error_details:
      allOf:
        - ref: '#/components/schemas/error_base'
        - title: Error Details
        - type: object
          properties:
            created:
              type: string
              format: date-time
              description: When the associated database model was initially created.
              example: 2015-09-10T15:24:53.503Z
            last_modified:
              type: string
              format: date-time
              description: When the associated database model was last saved.
              example: 2015-09-10T15:24:53.987Z