# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_auto_20170406_1517'),
        ('ingest', '0013_auto_20170313_1826'),
    ]

    operations = [
    ]
