# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-26 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_auto_20170412_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
