# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 18:11
from __future__ import unicode_literals

import datetime

import django.contrib.postgres.fields
from django.db import migrations, models

def populate_data_type_tags(apps, schema_editor):
    print('%s: starting populate_data_type_tags for ingest' % datetime.datetime.now())
    update = 'UPDATE ingest SET data_type_tags = {}'
    with connection.cursor() as cursor:
        cursor.execute(update)
        count = cursor.rowcount
        if count:
            print('%d entries updated with data type tags' % count)
    print('%s: finish populate_data_type_tags for ingest' % datetime.datetime.now())

    print ('Migration finished.')

class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_ingestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='data_type_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), null=True),
        ),
        migrations.RunPython(populate_data_type_tags),
        migrations.AlterField(
            model_name='ingest',
            name='data_type_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None),
        ),
    ]
