# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0017_populate_data_type_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingest',
            name='data_type',
        ),
    ]
