# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20170127_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalefile',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='json_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
