# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20170412_1225'),
        ('recipe', '0018_recipefile_recipe_input'),
        ('storage', '0007_auto_20170412_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalefile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batch.Batch'),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='job_output',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='recipe_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='recipe_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.RecipeType'),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='source_ended',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='source_started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
