# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20170609_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
