# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20171002_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scalefile',
            old_name='recipe_job',
            new_name='recipe_node',
        ),
    ]
