# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20180613_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalefile',
            name='source_collection',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='source_sensor',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='source_sensor_class',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scalefile',
            name='source_task',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
