# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_purgeresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='purgeresults',
            name='force_stop_purge',
            field=models.BooleanField(default=False),
        ),
    ]
