# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 18:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_purgeresults_force_stop_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalefile',
            name='data_type_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None),
        ),
    ]
