# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_jobtype_shared_mem_required'),
        ('job', '0023_auto_20170313_1826'),
    ]

    operations = [
    ]
