# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_auto_20170504_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_status_change',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
