# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_jobinputfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='mem_required',
            new_name='mem_const_required',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='mem_mult_required',
            field=models.FloatField(default=0.0),
        ),
    ]
