# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_auto_20170707_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='configuration',
        ),
    ]
