# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 20:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0004_error_should_be_retried'),
        ('node', '0004_auto_20170524_1639'),
        ('job', '0030_remove_job_configuration'),
        ('queue', '0015_auto_20170731_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecutionEnd',
            fields=[
                ('job_exe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='job.JobExecution')),
                ('exe_num', models.IntegerField()),
                ('status', models.CharField(choices=[('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], db_index=True, max_length=50)),
                ('queued', models.DateTimeField()),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended', models.DateTimeField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='error.Error')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.JobType')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='node.Node')),
            ],
            options={
                'db_table': 'job_exe_end',
            },
        ),
        migrations.CreateModel(
            name='JobExecutionOutput',
            fields=[
                ('job_exe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='job.JobExecution')),
                ('exe_num', models.IntegerField()),
                ('output_manifest', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.JobType')),
            ],
            options={
                'db_table': 'job_exe_output',
            },
        ),
        migrations.RenameField(
            model_name='jobexecution',
            old_name='disk_in_scheduled',
            new_name='input_file_size',
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='exe_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.JobType'),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='command_arguments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='environment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='job_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='last_modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='results_manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
