# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 17:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20180105_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=django.contrib.postgres.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name='job',
            name='results',
            field=django.contrib.postgres.fields.JSONField(blank=True, null=True)
        ),
        migrations.RenameField(
            model_name='job',
            old_name='disk_in_required',
            new_name='input_file_size',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='data',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='results',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cpus_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='disk_out_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='mem_required',
        ),
    ]
