# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 17:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20180105_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='cpus_required',
            new_name='input_file_size',
        ),
        migrations.RemoveField(
            model_name='job',
            name='data',
        ),
        migrations.RemoveField(
            model_name='job',
            name='disk_in_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='disk_out_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='mem_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='results',
        ),
        migrations.AddField(
            model_name='job',
            name='input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
