# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20180122_1444'),
        ('recipe', '0019_recipetype_is_system'),
        ('job', '0034_auto_20180112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_for_batch', to='batch.Batch'),
        ),
        migrations.AddField(
            model_name='job',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_for_recipe', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='job',
            name='root_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_for_root_recipe', to='recipe.Recipe'),
        ),
    ]
