# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20180122_1444'),
        ('recipe', '0020_recipe_batch'),
        ('job', '0035_auto_20180122_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexecution',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batch.Batch'),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.Recipe'),
        ),
    ]
