# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20180123_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexecutionend',
            name='seed_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexecutionend',
            name='seed_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
