# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 02:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_auto_20180314_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='cpus_required',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='custom_resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='disk_out_const_required',
            field=models.FloatField(default=64.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='disk_out_mult_required',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='docker_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='docker_privileged',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='error_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='mem_const_required',
            field=models.FloatField(default=64.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='mem_mult_required',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='revision_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='shared_mem_required',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='timeout',
            field=models.IntegerField(default=1800, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='uses_docker',
            field=models.NullBooleanField(default=True),
        ),
    ]
