# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_auto_20180622_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='priority',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
