# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-09 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_auto_20180622_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='archived',
            new_name='deprecated',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='interface',
            new_name='manifest',
        ),
        migrations.RenameField(
            model_name='jobtyperevision',
            old_name='interface',
            new_name='manifest',
        ),
    ]
