# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_auto_20180709_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, max_length=50)),
                ('tag', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
