# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_auto_20180802_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtypetag',
            name='job_type',
        ),
    ]
