# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_remove_jobtypetag_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtypetag',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='job.JobType'),
            preserve_default=False,
        ),
    ]
