# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_jobtypetag_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtyperevision',
            name='docker_image',
            field=models.TextField(default='not-a-real-image'),
        ),
    ]
