# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


def get_tagged_docker_image(manifest, docker_image):
    """Constructs a complete Docker image and tag with the correct packageVersion value
    """
    from job.models import JobInterfaceSunset
    from job.seed.manifest import SeedManifest

    interface = JobInterfaceSunset.create(manifest)
    if isinstance(interface, SeedManifest):
        # If Seed copy docker_image and compute the proper tag from package_version
        if ':' in docker_image:
            docker_image = docker_image.split(':', 1)[0]
        return '%s:%s' % (docker_image, interface.get_package_version())
    else:
        # If legacy just copy over docker_image to all revisions
        return docker_image


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0045_jobtyperevision_docker_image'),
    ]

    def populate_job_type_revision_docker_image(apps, schema_editor):
        # Go through all of the JobTypeRevision models and populate their docker_image
        JobTypeRevision = apps.get_model('job', 'JobTypeRevision')

        for job_type_rev in JobTypeRevision.objects.all().iterator():
            job_type = job_type_rev.job_type
            job_type_rev.docker_image = get_tagged_docker_image(job_type_rev.manifest, job_type.docker_image)
            job_type_rev.save()

    operations = [
        migrations.RunPython(populate_job_type_revision_docker_image),
    ]
