# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 14:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_jobtyperevision_docker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='version_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[None, None, None, None], size=4),
        ),
    ]
