# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_jobtyperevision_docker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='docker_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
