# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_auto_20180913_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='versionArray',
            new_name='version_array',
        ),
    ]
