# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_ingestevent'),
        ('job', '0050_job_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ingest_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingest.IngestEvent'),
        ),
        migrations.AlterField(
            model_name='job',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trigger.TriggerEvent'),
        ),
    ]
