# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 22:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0050_auto_20181109_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
