# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0051_auto_20190211_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
