# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0052_jobtype_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='unmet_resources',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
