# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-12 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0053_jobtype_unmet_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='job',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='author_url',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='cpus_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='custom_resources',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='disk_out_const_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='disk_out_mult_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='docker_params',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='docker_privileged',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='error_mapping',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='is_operational',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='mem_const_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='mem_mult_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='shared_mem_required',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='uses_docker',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='title',
        ),
    ]
