# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-03 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0056_auto_20190603_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobexecution',
            unique_together=set([('job', 'exe_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='jobexecutionend',
            unique_together=set([('job', 'exe_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='jobexecutionoutput',
            unique_together=set([('job', 'exe_num')]),
        ),
        migrations.AlterIndexTogether(
            name='jobexecution',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='jobexecutionend',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='jobexecutionoutput',
            index_together=set([]),
        ),
    ]
