# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0057_auto_20190603_1846')
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recipe_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_for_recipe_node', to='recipe.RecipeNode'),
        ),
    ]
