# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedresource',
            name='json_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
