# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 12:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedresource',
            name='json_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
