# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_resource', '0002_auto_20170412_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedresource',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='sharedresourcerequirement',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='sharedresourcerequirement',
            name='shared_resource',
        ),
        migrations.DeleteModel(
            name='SharedResource',
        ),
        migrations.DeleteModel(
            name='SharedResourceRequirement',
        ),
    ]
