# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_revert_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricserror',
            name='occurred',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metricsingest',
            name='occurred',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metricsjobtype',
            name='occurred',
            field=models.DateTimeField(db_index=True),
        ),
    ]
