# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_scheduler_queue_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
