# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_scheduler_num_message_handlers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='num_message_handlers',
            field=models.IntegerField(default=1),
        ),
    ]
