# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20171103_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='system_job_logging_level',
            field=models.CharField(default='INFO', max_length=10),
        ),
    ]
