# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_scheduler_debugging_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='resource_level',
            field=models.CharField(default='GOOD', max_length=10),
        ),
    ]
