# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20181220_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem', models.IntegerField(default=0)),
                ('gpus', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('cpus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cluster_resources',
            },
        ),
    ]
