# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_clusterresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterresources',
            name='cpus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterresources',
            name='disk',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterresources',
            name='gpus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterresources',
            name='mem',
            field=models.FloatField(default=0),
        ),
    ]
